In [225]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
df=pd.read_csv('yeast_csv.csv')
y=df.class_protein_localization.astype('category').cat.codes
df.drop(columns=['erl','pox','class_protein_localization'],inplace=True)
columns=df.columns
np.random.seed(0)
k = 9
# centroids[i] = [x, y]
centroids=[]
for i in range(k):
    centroids.append(np.random.uniform(size=len(columns)))
#df.drop(columns='class_protein_localization',inplace=True)
print(centroids)

[array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411]), array([0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
       0.52889492]), array([0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ,
       0.83261985]), array([0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936,
       0.78052918]), array([0.11827443, 0.63992102, 0.14335329, 0.94466892, 0.52184832,
       0.41466194]), array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 ]), array([0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ,
       0.43703195]), array([0.6976312 , 0.06022547, 0.66676672, 0.67063787, 0.21038256,
       0.1289263 ]), array([0.31542835, 0.36371077, 0.57019677, 0.43860151, 0.98837384,
       0.10204481])]

In [226]:
def centroid(df):
    sumd=0
    arr=[]
    import copy
    df1 = copy.deepcopy(df)
    for i in range(k):
        if i!=0:
            print(i)
            sumd = np.linalg.norm(df1.sub(np.array(centroids[i-1])), axis=1)
            
            #if(index!=)
            #print(len(sumd))
            index=int(np.argmax(sumd))
            print(index)
            print(df1.loc[index])

            #df.head(5)
            #print(index)
            #x=df['mcg'][index]
            #y=df['gvh'][index]
            for j in range(len(columns)):
                centroids[i][j]=df[columns[j]][index]
            df1.drop(index,axis=0,inplace=True)
centroid(df)
    
#print(centroids)

1
989
mcg    0.35
gvh    0.21
alm    1.00
mit    0.80
vac    0.13
nuc    0.01
Name: 989, dtype: float64
2
114
mcg    0.45
gvh    0.51
alm    0.50
mit    0.16
vac    0.52
nuc    1.00
Name: 114, dtype: float64
3
988
mcg    0.43
gvh    0.22
alm    0.79
mit    0.79
vac    0.22
nuc    0.00
Name: 988, dtype: float64
4
1076
mcg    0.77
gvh    0.82
alm    0.40
mit    0.36
vac    0.38
nuc    0.22
Name: 1076, dtype: float64
5
987
mcg    0.34
gvh    0.34
alm    0.65
mit    0.40
vac    0.32
nuc    0.16
Name: 987, dtype: float64
6
469
mcg    0.40
gvh    0.45
alm    0.42
mit    0.17
vac    0.54
nuc    0.26
Name: 469, dtype: float64
7
985
mcg    0.40
gvh    0.45
alm    0.61
mit    0.29
vac    0.44
nuc    0.22
Name: 985, dtype: float64
8
468
mcg    0.47
gvh    0.59
alm    0.43
mit    0.13
vac    0.56
nuc    0.30
Name: 468, dtype: float64

In [227]:
centroids

[array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411]),
 array([0.35, 0.21, 1.  , 0.8 , 0.13, 0.01]),
 array([0.45, 0.51, 0.5 , 0.16, 0.52, 1.  ]),
 array([0.43, 0.22, 0.79, 0.79, 0.22, 0.  ]),
 array([0.77, 0.82, 0.4 , 0.36, 0.38, 0.22]),
 array([0.34, 0.34, 0.65, 0.4 , 0.32, 0.16]),
 array([0.4 , 0.45, 0.42, 0.17, 0.54, 0.26]),
 array([0.4 , 0.45, 0.61, 0.29, 0.44, 0.22]),
 array([0.47, 0.59, 0.43, 0.13, 0.56, 0.3 ])]

In [228]:
#df.reset_index(drop=True).head(2)

In [229]:
df.shape

(1484, 6)

In [230]:
y.value_counts()

0    463
7    429
6    244
5    163
4     51
3     44
2     35
9     30
8     20
1      5
dtype: int64

In [231]:
for i in range(k):
    print(centroids[i])

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
[0.35 0.21 1.   0.8  0.13 0.01]
[0.45 0.51 0.5  0.16 0.52 1.  ]
[0.43 0.22 0.79 0.79 0.22 0.  ]
[0.77 0.82 0.4  0.36 0.38 0.22]
[0.34 0.34 0.65 0.4  0.32 0.16]
[0.4  0.45 0.42 0.17 0.54 0.26]
[0.4  0.45 0.61 0.29 0.44 0.22]
[0.47 0.59 0.43 0.13 0.56 0.3 ]

In [232]:
def assignment(df, centroids):
    k=9
    for i in range(k):
        x=0
        for j in range(len(columns)):
            
            x+=np.sqrt(np.abs((df[columns[j]] - centroids[i][j]) ** 2))
            #print()
                    
            
        # sqrt((x1 - x2)^2 - (y1 - y2)^2)
        df['distance_from_{}'.format(i)] =x
            
      
    centroid_distance_cols = ['distance_from_{}'.format(i) for i in range(k)]
    #print(centroid_distance_cols)
    df['closest'] = df.loc[:, centroid_distance_cols].idxmin(axis=1)
    #cluster_label.append(df.loc[:, centroid_distance_cols].idxmin(axis=1))
    df['closest'] = df['closest'].map(lambda x: int(x.lstrip('distance_from_')))
    #df['color'] = df['closest'].map(lambda x: colmap[x])  
    return df

In [233]:
df=assignment(df,centroids)

In [234]:
df.tail(5)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2,distance_from_3,distance_from_4,distance_from_5,distance_from_6,distance_from_7,distance_from_8,closest
1479,0.81,0.62,0.43,0.17,0.53,0.22,1.436262,2.68,1.34,2.29,0.61,1.47,0.64,0.97,0.52,8
1480,0.47,0.43,0.61,0.40,0.48,0.47,0.748362,1.94,1.02,1.55,1.29,0.73,0.78,0.49,0.86,7
1481,0.67,0.57,0.36,0.19,0.56,0.22,1.426262,2.57,1.27,2.18,0.74,1.36,0.53,0.86,0.43,8
1482,0.43,0.40,0.60,0.16,0.53,0.39,1.183889,2.09,0.85,1.70,1.48,0.88,0.41,0.48,0.55,6
1483,0.65,0.54,0.54,0.13,0.53,0.22,1.286262,2.37,1.09,1.98,0.92,1.16,0.55,0.66,0.45,8

In [235]:
df.iloc[:, :9].head(5)
#df.dropna(inplace=True)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2
0,0.58,0.61,0.47,0.13,0.48,0.22,1.166262,2.39,1.11
1,0.43,0.67,0.48,0.27,0.53,0.22,1.093889,2.20,1.10
2,0.64,0.62,0.49,0.15,0.53,0.22,1.226262,2.47,1.11
3,0.58,0.44,0.57,0.13,0.54,0.22,1.296262,2.18,1.10
4,0.42,0.44,0.48,0.54,0.48,0.22,1.013889,1.64,1.32

In [236]:
columns

Index(['mcg', 'gvh', 'alm', 'mit', 'vac', 'nuc'], dtype='object')

In [237]:
import copy

old_centroids = copy.deepcopy(centroids)

def update(l):
    for i in range(k):
        for j in range(len(columns)):
            centroids[i][j] = np.mean(df[df['closest'] == i][columns[j]])
        #centroids[i][8] = np.mean(df[df['closest'] == i]['TAX'])
    return l

centroids = update(centroids)

In [238]:
df = assignment(df, centroids)

In [239]:
df.tail(9)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2,distance_from_3,distance_from_4,distance_from_5,distance_from_6,distance_from_7,distance_from_8,closest
1475,0.71,0.50,0.50,0.18,0.46,0.22,0.915000,2.31,0.9080,1.92,0.546241,0.854815,0.513140,0.525137,0.422907,8
1476,0.61,0.48,0.54,0.25,0.50,0.22,0.765000,2.12,0.8252,1.73,0.600902,0.664815,0.424008,0.293074,0.347220,7
1477,0.38,0.32,0.64,0.41,0.44,0.11,1.163333,1.30,1.2308,1.01,1.268421,0.284074,0.785868,0.588905,1.047796,5
1478,0.38,0.40,0.66,0.35,0.43,0.11,1.173333,1.41,1.1208,1.12,1.158421,0.356296,0.675868,0.478905,0.937796,5
1479,0.81,0.62,0.43,0.17,0.53,0.22,1.052500,2.68,1.1804,2.29,0.360752,1.224815,0.712562,0.853074,0.451246,4
1480,0.47,0.43,0.61,0.40,0.48,0.47,0.543333,1.94,0.6708,1.55,1.090827,0.446296,0.605579,0.388568,0.788754,7
1481,0.67,0.57,0.36,0.19,0.56,0.22,0.948333,2.57,1.0704,2.18,0.536917,1.114815,0.602562,0.743074,0.375367,8
1482,0.43,0.40,0.60,0.16,0.53,0.39,0.931667,2.09,0.5544,1.70,1.173308,0.595556,0.330496,0.483874,0.603227,6
1483,0.65,0.54,0.54,0.13,0.53,0.22,0.893333,2.37,0.9488,1.98,0.650902,0.914815,0.547066,0.543074,0.361693,8

In [240]:
while True:
    closest_centroids = df['closest'].copy(deep=True)
    centroids = update(centroids)
    df = assignment(df, centroids)
    if closest_centroids.equals(df['closest']): #that is no change in the centroids
        break

In [241]:
df.head(15)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2,distance_from_3,distance_from_4,distance_from_5,distance_from_6,distance_from_7,distance_from_8,closest
0,0.58,0.61,0.47,0.13,0.48,0.22,0.703500,2.39,0.848302,2.00,0.563444,0.576884,0.510741,0.504112,0.229734,8
1,0.43,0.67,0.48,0.27,0.53,0.22,0.652000,2.20,0.702453,1.81,0.518874,0.486317,0.466481,0.428629,0.444053,7
2,0.64,0.62,0.49,0.15,0.53,0.22,0.763833,2.47,0.876981,2.08,0.488874,0.645609,0.586481,0.529289,0.248905,8
3,0.58,0.44,0.57,0.13,0.54,0.22,0.759333,2.18,0.704340,1.79,0.838874,0.376062,0.534815,0.486497,0.296243,8
4,0.42,0.44,0.48,0.54,0.48,0.22,0.303333,1.64,0.733774,1.27,0.956225,0.484391,0.569074,0.436853,0.703580,0
5,0.51,0.40,0.56,0.17,0.49,0.22,0.629333,1.99,0.577170,1.60,0.883444,0.166062,0.429074,0.400660,0.321272,5
6,0.50,0.54,0.48,0.65,0.53,0.22,0.218000,1.76,1.022453,1.37,0.881656,0.806317,0.786481,0.426904,0.624053,0
7,0.48,0.45,0.59,0.20,0.58,0.34,0.720500,2.16,0.484340,1.77,0.983113,0.342465,0.490926,0.487614,0.440266,5
8,0.55,0.50,0.66,0.36,0.49,0.22,0.479333,1.84,0.851132,1.45,0.756225,0.506771,0.670741,0.241320,0.462219,7
9,0.40,0.39,0.60,0.15,0.58,0.30,0.880500,2.02,0.548113,1.69,1.143113,0.282408,0.460926,0.647614,0.549320,5
10,0.43,0.39,0.54,0.21,0.53,0.27,0.650500,1.97,0.405849,1.58,0.913113,0.105156,0.340926,0.417614,0.390266,5
11,0.42,0.37,0.59,0.20,0.52,0.29,0.750500,1.91,0.445849,1.54,1.013113,0.152408,0.400926,0.517614,0.470266,5
12,0.40,0.42,0.57,0.35,0.53,0.25,0.557500,1.78,0.543585,1.45,0.865894,0.239972,0.444815,0.295838,0.561391,5
13,0.60,0.40,0.52,0.46,0.53,0.22,0.429333,1.87,0.821321,1.48,0.771656,0.536317,0.754815,0.354772,0.537189,7
14,0.66,0.55,0.45,0.19,0.46,0.22,0.703500,2.35,0.848302,1.96,0.483444,0.576884,0.480741,0.504112,0.260680,8

In [242]:
def prob(df,centroids):
    for i in range(k):
        z=0
        for j in range(len(columns)):
            z+=np.sqrt((df[columns[j]] - centroids[i][j])** 2)# sqrt((x1 - x2)^2 - (y1 - y2)^2)
                       
        df['Probability_{}'.format(i)] =(np.exp(-1*z))#/sum(df,centroids)

prob(df,centroids)
print(df.head())

    mcg   gvh   alm   mit   vac   nuc  distance_from_0  distance_from_1  \
0  0.58  0.61  0.47  0.13  0.48  0.22         0.703500             2.39
1  0.43  0.67  0.48  0.27  0.53  0.22         0.652000             2.20
2  0.64  0.62  0.49  0.15  0.53  0.22         0.763833             2.47
3  0.58  0.44  0.57  0.13  0.54  0.22         0.759333             2.18
4  0.42  0.44  0.48  0.54  0.48  0.22         0.303333             1.64

   distance_from_2  distance_from_3      ...        closest  Probability_0  \
0         0.848302             2.00      ...              8       0.494850
1         0.702453             1.81      ...              7       0.521003
2         0.876981             2.08      ...              8       0.465877
3         0.704340             1.79      ...              8       0.467978
4         0.733774             1.27      ...              0       0.738353

   Probability_1  Probability_2  Probability_3  Probability_4  Probability_5  \
0       0.091630       0.428141       0.135335       0.569245       0.561646
1       0.110803       0.495369       0.163654       0.595190       0.614887
2       0.084585       0.416037       0.124930       0.613316       0.524343
3       0.113042       0.494435       0.166960       0.432197       0.686560
4       0.193980       0.480094       0.280832       0.384341       0.616072

   Probability_6  Probability_7  Probability_8
0       0.600051       0.604042       0.794745
1       0.627205       0.651401       0.641431
2       0.556281       0.589023       0.779654
3       0.585778       0.614776       0.743607
4       0.566049       0.646067       0.494811

[5 rows x 25 columns]

In [243]:
from sklearn.metrics import silhouette_samples, silhouette_score
def score_metric(df):
   
    silhouette_avg = silhouette_score(df, np.array(df['closest']))
    print(silhouette_avg)#(-1,1) Higher the better
    
score_metric(df)

0.5533069640755183

In [244]:
df.shape

(1484, 25)

In [246]:
df.to_csv('KMEANSPP.csv')