In [327]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
df=pd.read_csv('yeast_csv.csv')
y=df.class_protein_localization.astype('category').cat.codes
df.drop(columns=['erl','pox','class_protein_localization'],inplace=True)
columns=df.columns
np.random.seed(1)
k = 9
# centroids[i] = [x, y]
centroids=[]
for i in range(k):
    centroids.append(np.random.uniform(size=len(columns)))

In [306]:
df.loc[0]

mcg    0.58
gvh    0.61
alm    0.47
mit    0.13
vac    0.48
nuc    0.22
Name: 0, dtype: float64

In [307]:
df.head(7)

    mcg   gvh   alm   mit   vac   nuc
0  0.58  0.61  0.47  0.13  0.48  0.22
1  0.43  0.67  0.48  0.27  0.53  0.22
2  0.64  0.62  0.49  0.15  0.53  0.22
3  0.58  0.44  0.57  0.13  0.54  0.22
4  0.42  0.44  0.48  0.54  0.48  0.22
5  0.51  0.40  0.56  0.17  0.49  0.22
6  0.50  0.54  0.48  0.65  0.53  0.22

In [308]:
y.value_counts()

0    463
7    429
6    244
5    163
4     51
3     44
2     35
9     30
8     20
1      5
dtype: int64

In [309]:
for i in range(k):
    print(centroids[i])

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02]
[0.18626021 0.34556073 0.39676747 0.53881673 0.41919451 0.6852195 ]
[0.20445225 0.87811744 0.02738759 0.67046751 0.4173048  0.55868983]
[0.14038694 0.19810149 0.80074457 0.96826158 0.31342418 0.69232262]
[0.87638915 0.89460666 0.08504421 0.03905478 0.16983042 0.8781425 ]
[0.09834683 0.42110763 0.95788953 0.53316528 0.69187711 0.31551563]
[0.68650093 0.83462567 0.01828828 0.75014431 0.98886109 0.74816565]
[0.28044399 0.78927933 0.10322601 0.44789353 0.9085955  0.29361415]
[0.28777534 0.13002857 0.01936696 0.67883553 0.21162812 0.26554666]

In [310]:
def assignment(df, centroids):
    k=9
    for i in range(k):
        x=0
        for j in range(len(columns)):
            
            x+=np.sqrt(np.abs((df[columns[j]] - centroids[i][j]) ** 2))
            
                    
            
        # sqrt((x1 - x2)^2 - (y1 - y2)^2)
        df['distance_from_{}'.format(i)] =x
            
      
    centroid_distance_cols = ['distance_from_{}'.format(i) for i in range(k)]
    #print(centroid_distance_cols)
    df['closest'] = df.loc[:, centroid_distance_cols].idxmin(axis=1)
    #cluster_label.append(df.loc[:, centroid_distance_cols].idxmin(axis=1))
    df['closest'] = df['closest'].map(lambda x: int(x.lstrip('distance_from_')))
    #df['color'] = df['closest'].map(lambda x: colmap[x])  
    return df

In [311]:
df=assignment(df,centroids)

In [312]:
df.head(5)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2,distance_from_3,distance_from_4,distance_from_5,distance_from_6,distance_from_7,distance_from_8,closest
0,0.58,0.61,0.47,0.13,0.48,0.22,1.376426,1.666253,2.02813,2.659416,2.025209,1.868993,2.440009,1.665713,2.085583,0
1,0.43,0.67,0.48,0.27,0.53,0.22,1.086426,1.496253,1.73813,2.469416,2.315209,1.578993,2.350009,1.275713,1.915583,0
2,0.64,0.62,0.49,0.15,0.53,0.22,1.476426,1.786253,2.12813,2.739416,2.045209,1.848993,2.320009,1.665713,2.205583,0
3,0.58,0.44,0.57,0.13,0.54,0.22,1.706426,1.656253,2.35813,2.449416,2.355209,1.538993,2.650009,1.875713,2.075583,5
4,0.42,0.44,0.48,0.54,0.48,0.22,1.461761,0.938620,1.63813,1.909416,2.775209,1.132663,2.370009,1.459925,1.355583,1

In [313]:
df.iloc[:, :].head(5)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2,distance_from_3,distance_from_4,distance_from_5,distance_from_6,distance_from_7,distance_from_8,closest
0,0.58,0.61,0.47,0.13,0.48,0.22,1.376426,1.666253,2.02813,2.659416,2.025209,1.868993,2.440009,1.665713,2.085583,0
1,0.43,0.67,0.48,0.27,0.53,0.22,1.086426,1.496253,1.73813,2.469416,2.315209,1.578993,2.350009,1.275713,1.915583,0
2,0.64,0.62,0.49,0.15,0.53,0.22,1.476426,1.786253,2.12813,2.739416,2.045209,1.848993,2.320009,1.665713,2.205583,0
3,0.58,0.44,0.57,0.13,0.54,0.22,1.706426,1.656253,2.35813,2.449416,2.355209,1.538993,2.650009,1.875713,2.075583,5
4,0.42,0.44,0.48,0.54,0.48,0.22,1.461761,0.938620,1.63813,1.909416,2.775209,1.132663,2.370009,1.459925,1.355583,1

In [314]:
columns

Index(['mcg', 'gvh', 'alm', 'mit', 'vac', 'nuc'], dtype='object')

In [315]:
import copy

old_centroids = copy.deepcopy(centroids)

def update(l):
    for i in range(k):
        for j in range(len(columns)):
            centroids[i][j] = np.mean(df[df['closest'] == i][columns[j]])
        #centroids[i][8] = np.mean(df[df['closest'] == i]['TAX'])
    return l

centroids = update(centroids)

In [316]:
df = assignment(df, centroids)

In [317]:
df.tail(9)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2,distance_from_3,distance_from_4,distance_from_5,distance_from_6,distance_from_7,distance_from_8,closest
1475,0.71,0.50,0.50,0.18,0.46,0.22,0.339210,0.544141,1.130,1.9125,0.751667,0.547512,1.66,0.630580,0.85,0
1476,0.61,0.48,0.54,0.25,0.50,0.22,0.270384,0.368863,0.980,1.7225,0.905000,0.277512,1.71,0.511594,0.74,0
1477,0.38,0.32,0.64,0.41,0.44,0.11,0.993138,0.723748,1.440,0.9025,1.725000,0.658710,2.21,1.151014,0.94,5
1478,0.38,0.40,0.66,0.35,0.43,0.11,0.883138,0.613748,1.450,1.0125,1.615000,0.548710,2.22,1.041014,0.99,5
1479,0.81,0.62,0.43,0.17,0.53,0.22,0.403070,0.846671,1.105,2.2825,0.401667,0.777512,1.31,0.508116,1.00,4
1480,0.47,0.43,0.61,0.40,0.48,0.47,0.836930,0.433166,0.935,1.5425,1.321667,0.472166,1.59,0.924348,0.98,1
1481,0.67,0.57,0.36,0.19,0.56,0.22,0.340971,0.736671,1.095,2.1725,0.511667,0.657834,1.40,0.460145,0.75,0
1482,0.43,0.40,0.60,0.16,0.53,0.39,0.730361,0.376184,1.210,1.6925,1.088333,0.387512,1.92,0.974928,0.75,1
1483,0.65,0.54,0.54,0.13,0.53,0.22,0.341512,0.618863,1.110,1.9725,0.791667,0.467512,1.70,0.550580,0.91,0

In [318]:
while True:
    closest_centroids = df['closest'].copy(deep=True)
    centroids = update(centroids)
    df = assignment(df, centroids)
    if closest_centroids.equals(df['closest']): #that is no change in the centroids
        break

In [319]:
df.head(15)

,mcg,gvh,alm,mit,vac,nuc,distance_from_0,distance_from_1,distance_from_2,distance_from_3,distance_from_4,distance_from_5,distance_from_6,distance_from_7,distance_from_8,closest
0,0.58,0.61,0.47,0.13,0.48,0.22,0.244956,0.860481,0.686923,2.26,0.537170,0.594778,1.52,0.512605,0.537901,0
1,0.43,0.67,0.48,0.27,0.53,0.22,0.448251,0.692019,0.640000,2.07,0.489434,0.520444,1.45,0.436279,0.466133,7
2,0.64,0.62,0.49,0.15,0.53,0.22,0.266297,0.886058,0.743333,2.34,0.459434,0.661056,1.42,0.547395,0.611492,0
3,0.58,0.44,0.57,0.13,0.54,0.22,0.292391,0.709135,0.756923,2.05,0.809434,0.395889,1.77,0.452093,0.565249,0
4,0.42,0.44,0.48,0.54,0.48,0.22,0.698688,0.726442,0.304957,1.51,0.949434,0.514167,1.45,0.430140,0.576298,2
5,0.51,0.40,0.56,0.17,0.49,0.22,0.298017,0.597212,0.637179,1.86,0.857170,0.185889,1.84,0.347302,0.461657,5
6,0.50,0.54,0.48,0.65,0.53,0.22,0.628251,1.012019,0.204615,1.63,0.871698,0.840444,1.13,0.452837,0.786133,2
7,0.48,0.45,0.59,0.20,0.58,0.34,0.425044,0.489135,0.738462,2.03,0.961509,0.347444,1.73,0.460837,0.492983,5
8,0.55,0.50,0.66,0.36,0.49,0.22,0.443003,0.839519,0.480513,1.71,0.749434,0.545278,1.61,0.221767,0.672541,7
9,0.40,0.39,0.60,0.15,0.58,0.30,0.530058,0.571442,0.898462,1.89,1.121509,0.245833,1.97,0.620837,0.488343,5
10,0.43,0.39,0.54,0.21,0.53,0.27,0.375044,0.422788,0.668462,1.84,0.891509,0.116111,1.80,0.390837,0.342983,5
11,0.42,0.37,0.59,0.20,0.52,0.29,0.455044,0.462788,0.768462,1.78,0.991509,0.151556,1.86,0.490837,0.402983,5
12,0.40,0.42,0.57,0.35,0.53,0.25,0.544344,0.547404,0.563590,1.65,0.863774,0.229556,1.71,0.260837,0.449890,5
13,0.60,0.40,0.52,0.46,0.53,0.22,0.537376,0.818750,0.426923,1.74,0.761698,0.570444,1.40,0.356047,0.759890,7
14,0.66,0.55,0.45,0.19,0.46,0.22,0.279942,0.860481,0.686923,2.22,0.457170,0.594778,1.44,0.512605,0.497901,0

In [320]:
def prob(df,centroids):
    for i in range(k):
        z=0
        for j in range(len(columns)):
            z+=np.sqrt((df[columns[j]] - centroids[i][j])** 2)# sqrt((x1 - x2)^2 - (y1 - y2)^2)
                       
        df['Probability_{}'.format(i)] =(np.exp(-1*z))#/sum(df,centroids)

prob(df,centroids)
print(df.head())

    mcg   gvh   alm   mit   vac   nuc  distance_from_0  distance_from_1  \
0  0.58  0.61  0.47  0.13  0.48  0.22         0.244956         0.860481
1  0.43  0.67  0.48  0.27  0.53  0.22         0.448251         0.692019
2  0.64  0.62  0.49  0.15  0.53  0.22         0.266297         0.886058
3  0.58  0.44  0.57  0.13  0.54  0.22         0.292391         0.709135
4  0.42  0.44  0.48  0.54  0.48  0.22         0.698688         0.726442

   distance_from_2  distance_from_3      ...        closest  Probability_0  \
0         0.686923             2.26      ...              0       0.782739
1         0.640000             2.07      ...              7       0.638745
2         0.743333             2.34      ...              0       0.766211
3         0.756923             2.05      ...              0       0.746477
4         0.304957             1.51      ...              2       0.497237

   Probability_1  Probability_2  Probability_3  Probability_4  Probability_5  \
0       0.422959       0.503122       0.104350       0.584400       0.551685
1       0.500564       0.527292       0.126186       0.612973       0.594256
2       0.412278       0.475526       0.096328       0.631641       0.516306
3       0.492070       0.469108       0.128735       0.445110       0.673081
4       0.483627       0.737155       0.220910       0.386960       0.597999

   Probability_6  Probability_7  Probability_8
0       0.218712       0.598934       0.583973
1       0.234570       0.646437       0.627424
2       0.241714       0.578455       0.542541
3       0.170333       0.636295       0.568219
4       0.234570       0.650418       0.561975

[5 rows x 25 columns]

In [321]:
from sklearn.metrics import silhouette_samples, silhouette_score
def score_metric(df):
   
    silhouette_avg = silhouette_score(df, np.array(df['closest']))
    print(silhouette_avg)#(-1,1) Higher the better
    
score_metric(df)

0.6033210982948796

In [326]:
df.to_csv('KMEANS.csv')